#IMPORT LIBRARIERS


In [1]:
import numpy as np
import torch 

In [2]:
#create a vector using numpy and convert it to a PyTorch tensor
nv = np.array([[1,2,3,4]]) # 2D array (1x4)])
print(nv), print('')

#transpose it
print(nv.T), print('')

#transpose the transpose
nvT = nv.T
print(nvT.T)# this will be the same as nv since it's a 1D array, no change in shape


[[1 2 3 4]]

[[1]
 [2]
 [3]
 [4]]

[[1 2 3 4]]


In [4]:
#repeat the matrix
nM = np.array([[1,2,3],[4,5,6]]) # 2D array (2x3)
print(nM), print('')

#Transpose the matrix nM
nM_T = nM.T
print(nM_T), print('')

# Transpose the transpose of nM, should be the same as original nM
nM_T_T = nM_T.T
print(nM_T_T) # this should be the same as nM

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


##  Using Pytorch


In [6]:
tv = torch.tensor([[1,2,3,4]])
print(tv), print(' ')

#transpose the tensor tv
print(tv.T), print(' ') # this will transpose the tensor, changing shape from (1,4) to (4,1)

#transpose the transpose of tv, should be the same as original tv
tv_T = tv.T
print(tv_T.T) # this should be the same as original tv, shape (1,4)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [7]:
#repeat the matrix
tM = torch.tensor([[1,2,3],[4,5,6]]) # 2D array (2x3)
print(tM), print('')

#Transpose the matrix nM
tM_T = tM.T
print(tM_T), print('')

# Transpose the transpose of nM, should be the same as original nM
tM_T_T = tM_T.T
print(tM_T_T) # this should be the same as nM

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
#examine the data types and shapes
print(f'Variable nv is of type {type(nv)} with shape {nv.shape}')
print(f'Variable tv is of type {type(tv)} with shape {tv.shape}')
print(f'Variable nM is of type {type(nM)} with shape {nM.shape}')
print(f'Variable tM is of type {type(tM)} with shape {tM.shape}')

Variable nv is of type <class 'numpy.ndarray'> with shape (1, 4)
Variable tv is of type <class 'torch.Tensor'> with shape torch.Size([1, 4])
Variable nM is of type <class 'numpy.ndarray'> with shape (2, 3)
Variable tM is of type <class 'torch.Tensor'> with shape torch.Size([2, 3])
