In [1]:
import numpy as np
import torch

## Using NUMPY

the @ symbol represents the matrix multiplication operator

In [2]:
# Create random matrices
A = np.random.rand(3, 4)  # 3x4 matrix with random values
B = np.random.rand(4, 5)  # 4x5 matrix with random values
C = np.random.rand(7, 3)  # 7x3 matrix with random values (corrected dimensions)

# Try some matrix multiplications
print(np.round(A @ B, 2)), print(' ')  # 3x5 matrix multiplication
print(np.round(C @ A, 2)), print(' ')  # 7x4 matrix multiplication
print(np.round(B.T @ A.T, 2)), print(' ')  # 5x3 matrix multiplication
#print(np.round(A @ C.T, 2)), print(' ')  # 3x7 matrix multiplication

[[1.61 1.61 0.68 1.04 1.43]
 [1.63 1.51 0.79 1.23 1.32]
 [1.12 1.28 0.28 0.74 0.99]]
 
[[1.   0.93 0.82 1.38]
 [0.95 0.97 0.74 0.63]
 [0.16 0.14 0.07 0.22]
 [0.8  0.82 0.56 0.48]
 [0.75 0.72 0.6  0.89]
 [1.03 0.97 0.86 1.38]
 [1.   1.01 0.92 0.78]]
 
[[1.61 1.63 1.12]
 [1.61 1.51 1.28]
 [0.68 0.79 0.28]
 [1.04 1.23 0.74]
 [1.43 1.32 0.99]]
 


(None, None)

In [7]:
# Create some random matrices
A_torch = torch.rand(3, 4)  # 3x4 matrix with random values
B_torch = torch.rand(4, 5)  # 4x5 matrix with random values
C1_torch = torch.rand(7, 3)  # 7x3 matrix with random values (corrected dimensions)
C2_torch = torch.rand(3, 7)  # 3x7 matrix with random values

# Try some matrix multiplications with PyTorch
print(torch.round(A_torch @ B_torch, decimals=2)), print(' ')  # 3x5 matrix multiplication
print(torch.round(C1_torch @ A_torch, decimals=2)), print(' ')  # 7x4 matrix multiplication
print(torch.round(B_torch.T @ A_torch.T, decimals=2)), print(' ')  # 5x3 matrix multiplication
#print(torch.round(A_torch @ C2_torch.T, decimals=2)), print(' ')  # 3x7 matrix multiplication

tensor([[0.5600, 0.5500, 0.9500, 1.0100, 1.5000],
        [0.7400, 0.4900, 1.3200, 1.0100, 1.6200],
        [0.6400, 0.6700, 1.1900, 1.2700, 1.5900]])
 
tensor([[0.9300, 0.7900, 0.5000, 0.3100],
        [0.8600, 0.6600, 0.5800, 0.2300],
        [0.6800, 0.6600, 0.4100, 0.2200],
        [0.5600, 0.4600, 0.2300, 0.2100],
        [0.6000, 0.6700, 0.3000, 0.2300],
        [1.0500, 0.9500, 0.4400, 0.4100],
        [1.5000, 0.9800, 0.8000, 0.4700]])
 
tensor([[0.5600, 0.7400, 0.6400],
        [0.5500, 0.4900, 0.6700],
        [0.9500, 1.3200, 1.1900],
        [1.0100, 1.0100, 1.2700],
        [1.5000, 1.6200, 1.5900]])
 


(None, None)